// File generated by FlutterFire CLI.
// This file is used to configure Firebase for the Flutter project.
// You will need to replace this with your own Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you need to create your own Firebase project and add the configuration.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you need to create your own Firebase project and add the configuration.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you need to create your own Firebase project and add the configuration.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you need to create your own Firebase project and add the configuration.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSREdWC0Vthtst2RiJqVUbvJ2UF796chw',
    appId: '1:124313429300:android:589427fd0bd8901e9af161',
    messagingSenderId: '124313429300',
    projectId: 'mujjarfunds',
    storageBucket: 'mujjarfunds.firebasestorage.app',
  );

  // Replace these placeholder values with your actual Firebase configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0A_XOCaiTTbaePkgQDKNIrdslBpK6hi8',
    appId: '1:124313429300:ios:c4f1678ad9301ea59af161',
    messagingSenderId: '124313429300',
    projectId: 'mujjarfunds',
    storageBucket: 'mujjarfunds.firebasestorage.app',
    iosBundleId: 'com.trakex.trakex',
  );

  // Replace these placeholder values with your actual Firebase configuration
}